name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cupti=10.1
  - cxx-compiler=1.0
  - ipython-sql=0.3
  - jupyterlab=1.2
  - jupyterlab-git=0.9
  - nccl=2.4
  - nvcc_linux-64=10.1
  - nodejs=13.0
  - openmpi=4.0
  - pip=19.3
  - pip:
    - -r file:requirements.txt
  - python=3.6
  - pytorch=1.4
  - tensorboard=2.0
  - torchvision=0.5
  
